name: Update Angular

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    branches:
      - develop

jobs:
  run:
    name: Update Angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - run: npm install
      
      - uses: itzrabbs/ng-update@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          base-branch: develop
