name: Release

on:
  push:
    branches: [master]

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14.15.x
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Build library
      run: npm run build:library
      
    - name: Publish to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./dist/angular-notifier/package.json
